// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDohU3zFSHAtXwGlFO0Vaw11aU8QxfcIrs',
    appId: '1:1096728850131:web:61ae7f1070be0b709dee26',
    messagingSenderId: '1096728850131',
    projectId: 'joseline-jimenez-9b',
    authDomain: 'joseline-jimenez-9b.firebaseapp.com',
    storageBucket: 'joseline-jimenez-9b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnW1QXTVKuPZJyfy6nrRZIS98HOS0IdYk',
    appId: '1:1096728850131:android:64ac07489e16b9509dee26',
    messagingSenderId: '1096728850131',
    projectId: 'joseline-jimenez-9b',
    storageBucket: 'joseline-jimenez-9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBteacRDe-AsKeyOVgLvmt45Q0YCTEX3BM',
    appId: '1:1096728850131:ios:6b5864c2b3121cae9dee26',
    messagingSenderId: '1096728850131',
    projectId: 'joseline-jimenez-9b',
    storageBucket: 'joseline-jimenez-9b.appspot.com',
    iosBundleId: 'com.example.fireJos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBteacRDe-AsKeyOVgLvmt45Q0YCTEX3BM',
    appId: '1:1096728850131:ios:6b5864c2b3121cae9dee26',
    messagingSenderId: '1096728850131',
    projectId: 'joseline-jimenez-9b',
    storageBucket: 'joseline-jimenez-9b.appspot.com',
    iosBundleId: 'com.example.fireJos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDohU3zFSHAtXwGlFO0Vaw11aU8QxfcIrs',
    appId: '1:1096728850131:web:f37a78e78820927b9dee26',
    messagingSenderId: '1096728850131',
    projectId: 'joseline-jimenez-9b',
    authDomain: 'joseline-jimenez-9b.firebaseapp.com',
    storageBucket: 'joseline-jimenez-9b.appspot.com',
  );
}
